#!/usr/bin/env bash
# Reconfigure /etc/hosts: localhost -> 127.0.0.2, facebook.com -> 8.8.8.8
sudo sed -i 's/^127\.0\.0\.1\s\+localhost/127.0.0.2 localhost/' /etc/hosts
echo -e "8.8.8.8\tfacebook.com" | sudo tee -a /etc/hosts > /dev/null
