#!/usr/bin/env bash
# Reconfigure /etc/hosts: localhost -> 127.0.0.2, facebook.com -> 8.8.8.8
new_hosts=$(sed 's/127\.0\.0\.1\s\+localhost/127.0.0.2 localhost/' /etc/hosts)
echo "$new_hosts" > /etc/hosts
echo -e "8.8.8.8\tfacebook.com" >> /etc/hosts
